---
title: "Projekt R"
author: "Tomasz Ancukiewicz 127219, Mikołaj Leśny 127218"
date: "18.11.2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Init libs
```{r}
library(dplyr)
library(tidyr)
library(mlbench)
library(caret)
library(pROC)
library(ggplot2)
```

# Data
Attribute Information:

 1. Class: no-recurrence-events, recurrence-events
 2. age: 10-19, 20-29, 30-39, 40-49, 50-59, 60-69, 70-79, 80-89, 90-99.
 3. menopause: lt40, ge40, premeno.
 4. tumor-size: 0-4, 5-9, 10-14, 15-19, 20-24, 25-29, 30-34, 35-39, 40-44,
                45-49, 50-54, 55-59.
 5. inv-nodes: 0-2, 3-5, 6-8, 9-11, 12-14, 15-17, 18-20, 21-23, 24-26,
               27-29, 30-32, 33-35, 36-39.
 6. node-caps: yes, no.
 7. deg-malig: 1, 2, 3.
 8. breast: left, right.
 9. breast-quad: left-up, left-low, right-up,	right-low, central.
10. irradiat:	yes, no.

# Load data
```{r}
data <- read.table('data/breast-cancer.data', sep = ',', header = F,
                   col.names = c('Class', 'age', 'menopause', 'tumor-size',
                                 'inv-nodes', 'node-caps', 'deg-malig', 'breast',
                                 'breast-quad', 'irradiat'))
data <- as.data.frame(data) %>%
  separate(age, into = paste("age", c('begin', 'end'), sep = ".")) %>%
  separate(tumor.size, into = paste("tumor.size", c('begin', 'end'), sep = ".")) %>%
  separate(inv.nodes, into = paste("inv.nodes", c('begin', 'end'), sep = "."))

levels(data$Class) <- c("no.recurrence.events", "recurrence.events")
levels(data$node.caps) <- c("any", "no", "yes")
levels(data$breast.quad) <- c("any", "central", "left.low", "left.up", "right.low", "right.up")

data$age.begin <- as.numeric(data$age.begin)
data$age.end <- as.numeric(data$age.end)

data$tumor.size.begin <- as.numeric(data$tumor.size.begin)
data$tumor.size.end <- as.numeric(data$tumor.size.end)

data$inv.nodes.begin <- as.numeric(data$inv.nodes.begin)
data$inv.nodes.end <- as.numeric(data$inv.nodes.end)
```

# Visualisation of data

Head
```{r}
head(data)
```

Summary
```{r}
summary(data)
```
Plots
```{r}
par(mfrow = c(3, 5), mar = c(4, 4, 2, 1))
barplot(table(data$Class))
hist(data$age.begin, breaks=5)
hist(data$age.end, breaks=5)
barplot(table(data$menopause))
hist(data$tumor.size.begin)
hist(data$tumor.size.end)
hist(data$inv.nodes.begin)
hist(data$inv.nodes.end)
barplot(table(data$node.caps))
hist(data$deg.malig, breaks=3)
barplot(table(data$breast))
barplot(table(data$breast.quad))
barplot(table(data$irradiat))
```


# Make test and train sets

```{r}
sizeOfClass <- round(nrow(filter(data, Class == 'recurrence.events')) * 0.7)

inTraining <- 1:sizeOfClass

recTrain <- filter(data, Class == 'recurrence.events')[inTraining,]
recTest <- filter(data, Class == 'recurrence.events')[-inTraining,]

noRecTrain <- filter(data, Class == 'no.recurrence.events')[inTraining,]
noRecTest <- filter(data, Class == 'no.recurrence.events')[-inTraining,]

training <- rbind(recTrain, noRecTrain)
testing <- rbind(recTest, noRecTest)
```

# Classification

```{r}
ctrl <- trainControl(method = "repeatedcv",
                     number = 5,
                     repeats = 5)

rfGrid <- expand.grid(mtry = 1:10, ntree = c(10, 100, 1000))

set.seed(23)
fitTune <- train(Class ~ .,
                 data = training,
                 method = "rf",
                 metric = "Accurancy",
                 preProc = c("center", "scale"),
                 trControl = ctrl,
                 ntree = 1000)
fitTune
rfClasses <- predict(fitTune, newdata = testing)
confusionMatrix(data = rfClasses, testing$Class)
```

ROC
```{r}
rfClasses <- predict(fitTune, newdata=testing, type="prob")
rfRoc <- roc(testing$Class, rfClasses$recurrence.events, levels=rev(levels(testing$Class)))
pROC::ggroc(rfRoc)
```
